config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create, :show, :index]
  resources :activities, only: [:index, :show, :update]
  resources :user_activities, only: [:create, :new, :destroy, :index, :show, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :activities
    resources :user_activities, only: [:create, :new, :destroy, :index, :show, :edit]
  end


end

app/models/activity.rb
class Activity < ApplicationRecord

  validates :title, uniqueness: true, presence: true
  validates_presence_of :points, require: true
  validates_presence_of :category, require: true

  has_many :user_activities
  has_many :users, through: :user_activities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/level.rb
class Level < ApplicationRecord

end

app/models/user.rb
# models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  enum role: %w(default admin)
  has_secure_password

  has_many :user_activities
  has_many :activities, through: :user_activities

  def points
    self.activities.sum(:points)
  end

  def level
    @level = Level.find_by("#{points} between min_score and max_score")
    @level ||= Level.first
  end

  def progress
    progress = ((points.to_f / level.max_score) * 100).round(2).to_s + '%'
    progress ||= 0
  end
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  def self.valid(params, current_user)
    last_event_date = select(:created_At).where("activity_id = ? AND user_id = ?", params[:activity_id], current_user).maximum(:created_at)
    return true unless last_event_date
    (Time.now - last_event_date) > 43200
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :require_user, only: [:show, :index]


  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def update
    activity = Activity.find(params[:id])
    activity.update(activity_params)
    redirect_to admin_activity_path(activity)
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :category, :points)
  end
  def require_user
    render file: "/public/404" unless current_user
  end

end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::BaseController
  def show
    @activity = Activity.find(params[:id])
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def destroy
    @activity = Activity.find(params[:id])
    Activity.destroy(@activity.id)
    flash.notice = "Activity #{@activity.title} Deleted"
    redirect_to admin_activities_path
  end

  def index
    @activities = Activity.all
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/user_activities_controller.rb
class Admin::UserActivitiesController < Admin::BaseController
  def new
    @user_activity = UserActivity.new
  end

  def index
    @activities = UserActivity.all
  end

  def show
    @activity = UserActivity.find(params[:id])
  end

  def edit
    @activity = UserActivity.find(params[:id])
  end

  def destroy
    activity = UserActivity.find(params[:id])
    UserActivity.destroy(activity.id)
    redirect_to admin_user_activities_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.notice = "Login success"
      redirect_to user_path(user)
    else
      render :new
      flash.notice = "Login Failed"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController
  before_action :require_user, only: [:show, :index, :new, :destroy]

  def new
    @user_activity = UserActivity.new
  end

  def create
    if UserActivity.valid(user_activity_params, current_user)
      UserActivity.create(activity_id: user_activity_params[:activity_id],user_id: current_user.id)
      redirect_to user_path(current_user.id)
    else
      redirect_to new_user_activity_path
      flash.notice = "You can only do that once a day"
    end
  end

  def index
    @activities = UserActivity.where(user_id: current_user.id)
  end

  def destroy
    UserActivity.destroy(params[:id])
    redirect_to user_activities_path
  end

  def show
    @user_activity = UserActivity.find(params[:id])
  end

  def update
    user_activity = UserActivity.find(params[:id])
    user_activity.update(user_activity_params)
    redirect_to admin_user_activity_path(user_activity)
  end

  private

  def user_activity_params
    params.require(:user_activity).permit(:activity_id)
  end

  def require_user
    render file: "/public/404" unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :index]

  def new
    @user = User.new
  end

  def index
    @users = User.all
    @users = @users.sort_by {|user| - user.points }

  end

   def show
    @user = User.find(params[:id])
   end


  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end

    def require_user
      render file: "/public/404" unless current_user
    end
end

app/controllers/welcome_controller.rb
# app/controllers/welcome_controller.rb

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<!-- views/users/show.html.erb -->

<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-2 align-items-center">
      </div>
      <div class="col-8">
        <div class="card text-center" >

          <div class="card-body">
            <h2>All Activities</h2>
            <div class='table-responsive'>


            <table class="table table-borderless">
              <tbody>
                <% @activities.each do |activity| %>
                <tr>
                  <td><%= activity.title %></td>
                  <td><%= activity.category %></td>
                  <td><%= activity.points %> Points</td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </br>
        </div>
      </div>
      <div class='col-2'>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px;">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>


<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px; background-color: #46b6ff">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<h1><%= @activity.title %></h1>
<h1><%= @activity.points %> Points</h1>
<h1><%= @activity.category %></h1>

app/views/admin/activities/edit.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-sm align-items-center">
      </div>
      <div class="col-sm">

        <div class="card text-center" >

          <div class="card-body">
            <h5 class="card-title h3" style="color: #68767F">Edit <%= @activity.title %></h5>

            <%= form_for @activity do |f| %>
            <div class="form-group">
              <%= f.label :Title %>
              <%= f.text_field :title %>
            </div>
            <div class="form-group">
              <%= f.label :category %>
              <%= f.text_field :category %>
            </div>
            <div class="form-group">
              <%= f.label :points %>
              <%= f.text_field :points %>
            </div>
            <%= f.submit "Edit", class: "btn btn-primary" %>
            <% end %>
            </br>
          </div>
          </br>
        </div>
      </div>
      <div class='col-sm'>
      </div>
    </div>
  </div>

</div>

app/views/admin/activities/index.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-2">
      </div>
      <div class="col-12">
        <div class="card text-center" >

          <div class="card-body">
            <h2>All Activities</h2>
            <div class='table-responsive'>


            <table class="table table-borderless">
              <tbody>
                <% @activities.each do |activity| %>
                <tr>
                  <td><%= activity.title %></td>
                  <td><%= activity.category %></td>
                  <td><%= activity.points %> Points</td>
                  <td><%= link_to 'Edit', edit_admin_activity_path(activity), class: 'btn btn-sm btn-outline-warning' %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </br>
        </div>
      </div>
      <div class='col-2'>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px;">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>


<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px; background-color: #46b6ff">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>

app/views/admin/activities/show.html.erb
<h1><%= @activity.title %></h1>

<h1><%= @activity.points %> Points</h1>
<h1><%= @activity.category %></h1>

<%= link_to 'Edit', edit_admin_activity_path(@activity) %>
<%= link_to 'Delete', admin_activity_path(@activity), method: :delete %>

app/views/admin/user_activities/edit.html.erb
<h1>Edit <%= @activity.id %></h1>
<%= form_for @activity do |f| %>
  <%= f.label :activity  %>
  <%= f.collection_select :activity_id, Activity.order(:title),:id,:title, include_blank: true %>
  <%= f.label :user %>
  <%= f.collection_select :user_id, User.order(:username),:id,:username, include_blank: true %>
  <%= f.submit%>
  <% end %>

app/views/admin/user_activities/index.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-2">
      </div>
      <div class="col-12">
        <div class="card text-center" >

          <div class="card-body">
            <div class='table-responsive'>


            <table class="table table-borderless">
              <tbody>
                <% @activities.each do |user_activity| %>
                <tr id="user-activity-<%= user_activity.id %>">
                  <td><%= user_activity.activity.title %></td>
                  <td><%= user_activity.user.username%></td>
                  <td><%= user_activity.created_at%></td>
                  <td><%= link_to 'Delete', user_activity_path(user_activity), method: :delete %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </br>
        </div>
      </div>
      <div class='col-2'>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px;">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>


<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px; background-color: #46b6ff">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>

app/views/admin/user_activities/new.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-sm align-items-center">
      </div>
      <div class="col-sm">

        <div class="card text-center" >

          <div class="card-body">
            <h5 class="card-title h3" style="color: #68767F">Record Activity</h5>

            <%= form_for @user_activity do |f| %>
            <div class="form-group">
              <%= f.label :Activity %>
              <%= f.collection_select :activity_id, Activity.order(:title),:id,:title, include_blank: true, class: 'custom-select' %>
            </div>
            <div class="form-group">
              <%= f.label :User %>
              <%= f.collection_select :user_id, User.order(:username),:id,:username, include_blank: true %>
            </div>
            <%= f.submit "Create", class: "btn btn-primary" %>
            <% end %>
            </br>
          </div>
          </br>
        </div>
      </div>
      <div class='col-sm'>
      </div>
    </div>
  </div>

</div>

app/views/admin/user_activities/show.html.erb
<h1>Create New User Activity</h1>
<ul>
  <li>ID: <%= @activity.id  %></li>
  <li>Activity ID: <%= @activity.activity_id  %></li>
  <li>User ID: <%= @activity.user_id  %></li>
  <li><%= link_to 'Edit', edit_admin_user_activity_path(@activity) %></li>
  <li><%= link_to 'Delete', admin_user_activity_path(@activity), method: :delete %></li>

</ul>

app/views/admin/users/index.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-2">
      </div>
      <div class="col-12">
        <div class="card text-center" >

          <div class="card-body">
            <h2>All Activities</h2>
            <div class='table-responsive'>


            <table class="table table-borderless">
              <tbody>
                <% @users.each do |user| %>
                  <tr id="user-<%= user.id %>">
                  <td><%=link_to user.username, admin_user_path(user) %></td>
                  <td><%=link_to 'Delete', admin_user_path(user), method: :delete %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </br>
        </div>
      </div>
      <div class='col-2'>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px;">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>


<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px; background-color: #46b6ff">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!-- views/users/show.html.erb -->
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;"></br>
</br>
</br>
<div class="container">
<div class="row ">
<div class="col-sm align-items-center">
  <%=image_tag("usr.png", style: 'height: 30vh;')%>
</div>
<div class="col-sm">
  <h1 class="display-1 text-white"><%= @user.username %></h1>
  <h3 class="display-4 textiwhite"><%=@user.points %>
    Points</h3>

  <% if @user == current_user %>
    <%= link_to 'Add Activity', new_user_activity_path, class: 'btn btn-success' %>
  <% end %>
    <%= link_to 'Delete', admin_user_path(@user), method: :delete, class: 'btn btn-danger' %>
</div>
<div class='col-sm'>
  <br/>
  <h3 class="display-4 text-center text-white">Level
    <%= @user.level.level %>
  </h3>
  <hr>
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= @user.progress %>" aria-valuenow=<%= @user.points %> aria-valuemin=<%= @user.level.min_score %> aria-valuemax=<%= @user.level.max_score %>></div>
  </div>
  <hr>
  <em>
    <p class='text-white text-center'><%= @user.points %>/
      <%= @user.level.max_score %></p>
  </em>
</div>
</div>
</br>
<div class="row">
<div class="col-12">
  <div class="card text-center">
    <div class="card-body">
      <h2>Activities</h2>
      <div class='table-responsive'>
        <table class="table table-borderless">
          <tbody>
            <% @user.activities.each do |activity| %>
              <tr>
                <td><%= activity.title %></td>
                <td><%= activity.category %></td>
                <td><%= activity.points %>
                  Points</td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
</div>

</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 100%; margin-top: 0px;"></br>
</br>
</br>
<div class="container">
<div class="row ">
<div class="col-sm align-items-center"></div>
<div class="col-sm"></div>
<div class='col-sm'></div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115621963-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115621963-2');
</script>

    <title>Adultish</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body style="background-color: #e0e3e5;">
    <div style='background-color: #46B6FF'>
    <% if current_user.nil? %>
     <!--Anon Navbar Area -->
      <nav class="navbar sticky-top navbar-expand-sm navbar-light ">
    <a class="nav-link h3" href="<%= root_path %>">  Adultish  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    </ul>
    <span class="navbar-text">
        <%= link_to "Sign Up", new_user_path, class: 'nav-link' %>
    </span>
    <span>|</span>
    <span class="navbar-text">
        <%= link_to "Login", login_path, class: 'nav-link'%>
    </span>
  </div>
</nav>
<% elsif current_user.admin? %>

  <!-- Admin Navbar Area-->
      <nav class="navbar navbar-expand-sm sticky-top navbar-light ">
    <a class="nav-link h3" href="<%= root_path %>">  Adultish  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', user_path(current_user), class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Activities', admin_activities_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Leaderboard', admin_users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'User Activities', admin_user_activities_path, class: 'nav-link' %>
      </li>
    </ul>
    <span class="navbar-text">
        <%= link_to "Log Out", logout_path, class: 'nav-link'%>
    </span>
  </div>
</nav>

<% else %>


  <!-- User Navbar Area-->

      <nav class="navbar navbar-expand-sm navbar-light sticky-top">
    <a class="nav-link h3" href="<%= root_path %>">  Adultish  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', user_path(current_user), class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Leaderboard', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Activities', activities_path, class: 'nav-link' %>
      </li>
    </ul>
    <span>

    <% if flash.notice %>
      <p class="alert alert-success" role="alert"><%= flash.notice%></p>
    <% end %>
    </span>
    <span class="navbar-text">
        <%= link_to "Log Out", logout_path, class: 'nav-link'%>
    </span>
  </div>

</nav>

<% end %>
  </div>
      <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/user_activities/index.html.erb
<h1>Activities for <%= current_user.username %></h1>


<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; height: 80vh; margin-bottom: 0px;">
  </br>
  </br>
  </br>
  <div class="container">
    <div class="row ">
      <div class="col-2">
      </div>
      <div class="col-12">
        <div class="card text-center" >

          <div class="card-body">
            <h1>Activities for <%= current_user.username %></h1>
            <div class='table-responsive'>


            <table class="table table-borderless">
              <tbody>
                <% @activities.each do |user_activity| %>
                <tr>
                  <td><%= user_activity.activity.title %></td>
                  <td><%= link_to 'Delete', user_activity_path(user_activity), method: :delete %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </br>
        </div>
      </div>
      <div class='col-2'>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px;">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>


<div class="jumbotron jumbotron-fluid align-items-center" style="height: 80vh; margin-top: 0px; background-color: #46b6ff">
  <div class="container">
    <div class="row ">
    </div>
  </div>
</div>

app/views/user_activities/show.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF; margin-bottom: 0px;"></br>
</br>
</br>
  <div class="container">
    <div class="row ">
      <div class="col-sm align-items-center">
      </div>
      <div class="col-sm">
        <h1 class="display-1 text-white"><%= @user_activity.activity.title %></h1>
        <h3 class="display-4 textiwhite"><%=@user_activity.activity.points %> Points</h3>
        <h3 class="display-4 textiwhite">Completed By<%= @user_activity.user.username%></h3>
        <% if @user_activity.user == current_user %>
          <%= link_to 'Delete', user_activity_path(@user_activity), method: :delete, class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class='col-sm'>
      </div>
    </div>
    </br>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron jumbotron-fluid align-items-center" style="background-color: #46B6FF">
  <div class="container">
    <div class="row align-items-center" id="main-jumbo">
      <div class="col-sm">
      </div>
      <div class="col-sm">
        <h1 class="display-1 text-white">Adultish</h1>
        <p class="lead">Because being an adult sucks and games don't. Earn points and level up by doing the adult things you're supposed to do every day.</p>
        <%= link_to 'Sign Up', new_user_path, class: "btn btn-outline-dark btn-lg" %>
      </div>
      <div class="col-sm">
      </div>
</div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid align-items-center" >
  <div class="container">
    <div class="row align-items-center">
      <div class="col-sm">
        <div class="card text-center" style="min-height: 25vh">

          <div class="card-body">
            <h5 class="card-title h3" style="color: #68767F">Activities</h5>
            <p class="card-text">Complete the activities that you're supposed to do as an adult to earn points!</p>
            <ul style="text-align: left">
              <li> Do a load of laundry: <strong>25 Points</strong></li>
              <li> Mow the Lawn: <strong>50 Points</strong></li>
              <li> Pay Rent: <strong>500 Points</strong></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card text-center" style="min-height: 25vh">
          <div class="card-body">
            <h5 class="card-title h3" style="color: #68767F">Level Up</h5>
            <p class="card-text">As you earn points you will level up!</p>
            </br>
            <p class="card-text"><strong>Level 14</strong></p>
            <div class="progress">
              <div class="progress-bar progress-bar-striped bg-#46B6FF" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <p class="card-text"><em>6250 / 25000</em></p>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card text-center", style="min-height: 25vh">
          <div class="card-body">
            <h5 class="card-title h3" style="color: #68767F">Compete</h5>
            <p class="card-text">Compete with your friends and others in the community to see who really is the most grown up.</p>
          </div>
        </div>
      </div>
</div>
  </div>
</div>